features/infinite scroll
yurii-kozlov/tech-online-shop pull request #22
Opened 2023-01-23 11:31 UTC by yurii-kozlov

2023-01-23 11:33 UTC, yurii-kozlov commented on api/api.ts
> +const BASE_URL = 'http://localhost:3002';
I tried to use the env variable (BASE_URL) but somehow it didn't work. Should I leave it like that or would ii be better to somehow replace it with the env variable?

2023-01-23 11:36 UTC, yurii-kozlov commented on components/ProductsScroll/ProductsScroll.tsx
> +  const scrollHandler = (e: any):void => {
If I implemented the logic in the right way, could you please give me a hint how to type this event? I was puzzling over it for a long time and wasn't able to find or guess the answer

2023-01-24 11:57 UTC, TechCossack requested changes

2023-01-24 11:57 UTC, TechCossack commented on api/api.ts
> +const BASE_URL = 'http://localhost:3002';
Pls, read the NextJs documentation and use env variable https://nextjs.org/docs/basic-features/environment-variables

2023-01-24 11:57 UTC, TechCossack commented on components/ProductsScroll/Computers/Computers.tsx
> +    if (fetching && computers.length < 60 && visibleProductSection === Goods.computers) {
this is not good, pls tell me what is going on here))

2023-01-24 11:57 UTC, TechCossack commented on components/ProductsScroll/Laptops/Laptops.tsx
> +    if (fetching && laptops.length < 60 && visibleProductSection === Goods.laptops) {
the same)

2023-01-24 11:57 UTC, TechCossack commented on components/ProductsScroll/ProductsScroll.tsx
> +  const handleLaptopsVisibility = (): void => setVisibleProductSection(Goods.laptops);
and pls describe me this logic too

2023-01-24 11:57 UTC, TechCossack commented on components/ProductsScroll/ProductsScroll.tsx
> +  const scrollHandler = (e: any):void => {
let's discuss it in haddle

2023-01-26 13:43 UTC, TechCossack approved these changes

2023-01-26 15:29 UTC, merged