features/aboutProductPage
yurii-kozlov/tech-online-shop pull request #26
Opened 2023-01-26 15:21 UTC by yurii-kozlov

2023-01-26 19:17 UTC, TechCossack requested changes

2023-01-26 19:17 UTC, TechCossack commented on components/AboutProduct/Details.tsx
> +  const getTheRightDetailsList = (productKind: Goods): string[] => {
this is smth strange)) can you describe?)

2023-01-26 19:24 UTC, yurii-kozlov commented on components/AboutProduct/Details.tsx
> +  const getTheRightDetailsList = (productKind: Goods): string[] => {
> this is smth strange)) can you describe?)

I need to receive the list of features from the paragraph. And depending on the product type I split the paragraph))

2023-01-27 10:43 UTC, RuchkoVlad approved these changes

2023-01-27 10:48 UTC, merged